export const MITRE_TACTICS_AND_TECHNIQUES = {
  "Reconnaissance": [
    "Active Scanning",
    "Gather Victim Host Information",
    "Gather Victim Identity Information",
    "Gather Victim Network Information", 
    "Gather Victim Organizational Information",
    "Phishing for Information",
    "Search Closed Sources",
    "Search Open Technical Databases",
    "Search Open Websites/Domains",
    "Search Victim-Owned Websites"
  ],
  "Resource Development": [
    "Acquire Access",
    "Acquire Infrastructure",
    "Compromise Accounts",
    "Compromise Infrastructure", 
    "Develop Capabilities",
    "Establish Accounts",
    "Obtain Capabilities",
    "Stage Capabilities"
  ],
  "Initial Access": [
    "Drive-by Compromise",
    "Exploit Public-Facing Application",
    "External Remote Services", 
    "Hardware Additions",
    "Phishing",
    "Replication Through Removable Media",
    "Supply Chain Compromise",
    "Trusted Relationship",
    "Valid Accounts"
  ],
  "Execution": [
    "Command and Scripting Interpreter",
    "Container Administration Command",
    "Deploy Container",
    "Exploitation for Client Execution",
    "Inter-Process Communication",
    "Native API",
    "Scheduled Task/Job",
    "Shared Modules",
    "Software Deployment Tools",
    "System Services",
    "User Execution",
    "Windows Management Instrumentation"
  ],
  "Persistence": [
    "Account Manipulation",
    "BITS Jobs",
    "Boot or Logon Autostart Execution",
    "Browser Extensions",
    "Compromise Client Software Binary",
    "Create Account",
    "Create or Modify System Process",
    "Event Triggered Execution",
    "External Remote Services",
    "Hijack Execution Flow",
    "Implant Internal Image",
    "Office Application Startup",
    "Pre-OS Boot",
    "Scheduled Task/Job",
    "Server Software Component",
    "Traffic Signaling",
    "Valid Accounts"
  ],
  "Privilege Escalation": [
    "Abuse Elevation Control Mechanism",
    "Access Token Manipulation",
    "Boot or Logon Autostart Execution",
    "Domain Policy Modification",
    "Escape to Host",
    "Event Triggered Execution",
    "Exploitation for Privilege Escalation",
    "Hijack Execution Flow",
    "Process Injection",
    "Scheduled Task/Job",
    "Valid Accounts"
  ],
  "Defense Evasion": [
    "Abuse Elevation Control Mechanism",
    "Access Token Manipulation",
    "Build Image on Host",
    "Deobfuscate/Decode Files or Information",
    "Deploy Container",
    "Direct Volume Access",
    "Domain Policy Modification",
    "Execution Guardrails",
    "Exploitation for Defense Evasion",
    "File and Directory Permissions Modification",
    "Hide Artifacts",
    "Hijack Execution Flow",
    "Impair Defenses",
    "Indicator Removal",
    "Indirect Command Execution",
    "Masquerading",
    "Modify Authentication Process",
    "Modify Registry",
    "Network Boundary Bridging",
    "Obfuscated Files or Information",
    "Pre-OS Boot",
    "Process Injection",
    "Rootkit",
    "Subvert Trust Controls",
    "Template Injection",
    "Traffic Signaling",
    "Valid Accounts",
    "Virtualization/Sandbox Evasion",
    "Weaken Encryption"
  ],
  "Credential Access": [
    "Adversary-in-the-Middle",
    "Brute Force",
    "Credentials from Password Stores",
    "Exploitation for Credential Access",
    "Forced Authentication",
    "Forge Web Credentials",
    "Input Capture",
    "Modify Authentication Process",
    "Multi-Factor Authentication Interception",
    "Network Sniffing",
    "OS Credential Dumping",
    "Steal Application Access Token",
    "Steal or Forge Authentication Certificates",
    "Steal or Forge Kerberos Tickets",
    "Steal Web Session Cookie",
    "Unsecured Credentials"
  ],
  "Discovery": [
    "Account Discovery",
    "Application Window Discovery",
    "Browser Information Discovery",
    "Cloud Infrastructure Discovery",
    "Cloud Service Discovery",
    "Domain Trust Discovery",
    "File and Directory Discovery",
    "Network Service Discovery",
    "Network Share Discovery",
    "Password Policy Discovery",
    "Permission Groups Discovery",
    "Process Discovery",
    "Query Registry",
    "Remote System Discovery",
    "Software Discovery",
    "System Information Discovery",
    "System Network Configuration Discovery",
    "System Owner/User Discovery",
    "System Service Discovery",
    "System Time Discovery",
    "Virtualization/Sandbox Evasion"
  ],
  "Lateral Movement": [
    "Exploitation of Remote Services",
    "Internal Spearphishing",
    "Lateral Tool Transfer",
    "Remote Service Session Hijacking",
    "Remote Services",
    "Replication Through Removable Media",
    "Software Deployment Tools",
    "Taint Shared Content",
    "Use Alternate Authentication Material"
  ],
  "Collection": [
    "Adversary-in-the-Middle",
    "Archive Collected Data",
    "Audio Capture",
    "Automated Collection",
    "Browser Session Hijacking",
    "Clipboard Data",
    "Data from Cloud Storage",
    "Data from Configuration Repository",
    "Data from Information Repositories",
    "Data from Local System",
    "Data from Network Shared Drive",
    "Data from Removable Media",
    "Data Staged",
    "Email Collection",
    "Input Capture",
    "Screen Capture",
    "Video Capture"
  ],
  "Command and Control": [
    "Application Layer Protocol",
    "Communication Through Removable Media",
    "Data Encoding",
    "Data Obfuscation",
    "Dynamic Resolution",
    "Encrypted Channel",
    "Fallback Channels",
    "Ingress Tool Transfer",
    "Multi-Stage Channels",
    "Non-Application Layer Protocol",
    "Non-Standard Port",
    "Protocol Tunneling",
    "Proxy",
    "Remote Access Software",
    "Traffic Signaling",
    "Web Service"
  ],
  "Exfiltration": [
    "Automated Exfiltration",
    "Data Transfer Size Limits",
    "Exfiltration Over Alternative Protocol",
    "Exfiltration Over C2 Channel",
    "Exfiltration Over Other Network Medium",
    "Exfiltration Over Physical Medium",
    "Exfiltration Over Web Service",
    "Scheduled Transfer",
    "Transfer Data to Cloud Account"
  ],
  "Impact": [
    "Account Access Removal",
    "Data Destruction",
    "Data Encrypted for Impact",
    "Data Manipulation",
    "Defacement",
    "Disk Wipe",
    "Endpoint Denial of Service",
    "Firmware Corruption",
    "Inhibit System Recovery",
    "Network Denial of Service",
    "Resource Hijacking",
    "Service Stop",
    "System Shutdown/Reboot"
  ]
};

export const getTechniqueId = (technique: string): string => {
  // This is a simplified version - you might want to add a proper mapping
  return technique.toUpperCase().replace(/\s+/g, '');
};